**作用：** 捕获错误，并进行处理

**触发条件：** 项目中发生错误后触发

**解决：** 解决发生错误后代码不会往下执行，导致无法响应的问题

**特性：**
1、必须包含 err、req、res、next 这四个形参
2、必须放在所有路由的最后面
3、只能捕获同步代码出错

**例子：**
```js
const Express = require('express')
var app = Express()

app.get('/', (req, res) => {
  throw new Error('这是手动制造的错误。因为我发送错误了，所以不会执行下面的代码')
  res.send('get')
})

// 全局错误级别中间件
app.use((err, req, res, next) => {
  console.log('发送了错误：' + err.message)
  res.send('Error!' + err.message)
})
```